# serverless.yml
service: sml

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  memorySize: 128

functions:
  rest:
    handler: index.handler
    events:
      - http:
          path: jobs
          method: get
      - http:
          path: jobs/{id}
          method: get
      - http:
          path: jobs
          method: post
      - http:
          path: jobs/{id}
          method: put
      - http:
          path: jobs/{id}
          method: delete
      - http:
          path: users
          method: get
      - http:
          path: users/{id}
          method: get
      - http:
          path: users
          method: post
      - http:
          path: users
          method: put
      - http:
          path: users
          method: delete
      - http:
          path: sites
          method: get
      - http:
          path: sites/{id}
          method: get
      - http:
          path: customers
          method: get
      - http:
          path: customers
          method: post
      - http:
          path: reports
          method: post
      - http:
          path: reports
          method: delete
